#+title:      Climbing wall build 2023
#+date:       [2023-05-10 Wed 19:03]
#+filetags: :climbing:dad:gym:paps:
#+identifier: 20230510T190345

M10 T-nuts which have an outer diameter of 12 mm

What type of wood you used for the 2x6 frame?

Pine on both the 22mm plywood and the 2x6 frame.

For the T-nuts, here's a nice link from Amazon: https://www.amazon.es/ALPIDEX-Tuercas-dientes-acero-galvanizado/dp/B07JC71FN6

250 t-nuts (tuercas) for 25€.

Also found holds and you can include all the bolts tnuts and the rest for 40€ more: https://eclipsepresas.com/iniciacion-presas-de-escalada-perfectas-para-la-iniciacion/74-presas-de-buen-canto-para-desplome.html


Necesitamos madera de pino, tanto contrachapado como 2x6 (3.8cm x 14cm) para el frame:
- Frame:
  - 6 x 2.4m largo
  - 8 x 44.3cm largo
  - 10 x 36.2cm largo
  - 4 x 56.2cm largo

- Plywood 22mm grosor: 2 x 1.2m ancho x 2.4m largo
  https://euroholds.com/es/ofertas-promociones/196-pack-iniciacion-tornillo-allen.html

I imagine that we could use the "tuerca enjaulada" to get the same feeling that Lonestar bolts support, basically turning bolt-on holds to screw-on holds: https://www.tornillos-express.es/tuerca-jaula-redondo-grosor-de-ajuste-cv/32426-tuerca-jaula-redondo-m5-grosor-de-ajuste-07a4-cv4825hg-acero-cincado-blanco-3663072342804.html
It shouldn't work, it doesn't support the actual screw on it. I wonder what people in the uk do for that.

T-nuts that are better screwed-on compared to the actual banging of the t-nuts: https://euroholds.com/es/tuercas/22-tuerca-atornillar-10mm-8432393111568.html Not that expensive either, we can have 150 for 25 bucks, and better than the other ones.

This is the link for the drill head (drill bits) with the countersink for making the actual holds on the wall.
